/* data_loader.js - A股历史行情数据管道（Node.js，无第三方依赖） */
import fs from 'node:fs/promises';
const UA='Mozilla/5.0';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function secid(code){return /^(6|9)/.test(code)?`1.${code}`:`0.${code}`;}
function marketCode(code){return /^(6|9)/.test(code)||code==='000300'?`sh${code}`:`sz${code}`;}
function n(v){const x=Number(v);return Number.isFinite(x)?x:null;}
function dateText(d){return d.toISOString().slice(0,10);}
async function getJson(url,params={}){const u=new URL(url);for(const[k,v]of Object.entries(params))u.searchParams.set(k,String(v));const res=await fetch(u,{headers:{'User-Agent':UA,Referer:'https://quote.eastmoney.com/'}});if(!res.ok)throw new Error(`行情接口失败 ${res.status}: ${u}`);return res.json();}
async function fetchTencentKlines(code,period,years){const interval=period===101?'day':period===15?'15m':'day',count=period===101?Math.max(600,years*280):10000;const u=new URL('https://web.ifzq.gtimg.cn/appstock/app/fqkline/get');u.searchParams.set('param',`${marketCode(code)},${interval},,,${count},qfq`);const res=await fetch(u,{headers:{'User-Agent':UA,Referer:'https://gu.qq.com/'} });if(!res.ok)throw new Error(`腾讯行情接口失败 ${res.status}`);const json=await res.json(),data=json.data?.[marketCode(code)]||{},rows=data[interval]||data[`qfq${interval}`]||[];return rows.map(row=>({date:row[0],open:n(row[1]),close:n(row[2]),high:n(row[3]),low:n(row[4]),volume:n(row[5]),amount:n(row[6])||0})).filter(x=>[x.open,x.high,x.low,x.close,x.volume].every(Number.isFinite));}
export async function fetchKlines(code,{period=101,years=2}={}){const end=new Date(),begin=new Date(end);begin.setFullYear(begin.getFullYear()-years);let data;try{data=await getJson('https://push2his.eastmoney.com/api/qt/stock/kline/get',{secid:secid(code),klt:period,fqt:1,beg:dateText(begin).replaceAll('-',''),end:dateText(end).replaceAll('-',''),lmt:10000,fields1:'f1,f2,f3,f4,f5,f6',fields2:'f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61'});}catch(error){console.warn(`[数据源降级] 东方财富不可用，切换腾讯财经：${code} / ${period}`);return fetchTencentKlines(code,period,years);}const rows=data.data?.klines||[];return rows.map(line=>{const[date,open,close,high,low,volume,amount,amplitude,changePct,change,turnover]=line.split(',');return{date,open:n(open),high:n(high),low:n(low),close:n(close),volume:n(volume),amount:n(amount),amplitude:n(amplitude),changePct:n(changePct),change:n(change),turnover:n(turnover)};}).filter(x=>[x.open,x.high,x.low,x.close,x.volume].every(Number.isFinite));}
export function cleanBars(bars){const seen=new Set();return bars.filter(b=>{if(seen.has(b.date))return false;seen.add(b.date);return b.high>=Math.max(b.open,b.close)&&b.low<=Math.min(b.open,b.close)&&b.volume>=0;}).sort((a,b)=>a.date.localeCompare(b.date));}
export async function loadSymbol(code,config){const daily=cleanBars(await fetchKlines(code,{period:101,years:config.years}));await sleep(300);const intraday15m=cleanBars(await fetchKlines(code,{period:15,years:1}));return{code,daily,intraday15m};}
export async function loadBenchmark(config){return cleanBars(await fetchKlines('000300',{period:101,years:config.years}));}
export async function saveJson(file,data){await fs.writeFile(file,JSON.stringify(data,null,2),'utf8');}
